const questions=[
{q:`Desreconhecimento é a retirada de parte ou da totalidade de ativo ou passivo reconhecido do balanço patrimonial da entidade. A máquina utilizada para a produção do principal produto de uma entidade deve ser desreconhecida quando`,o:[`perder todo o potencial de produzir benefícios econômicos para a entidade.`,`estiver parcialmente depreciada.`,`sofrer perda de valor recuperável.`,`estiver sob controle da entidade.`],a:'A'},
{q:`Conforme a NBC TG – Estrutura Conceitual, uma receita reflete aumento nos ativos, ou redução nos passivos, que resultam em aumentos no patrimônio líquido, exceto contribuições de detentores de direitos sobre o patrimônio.\n\nConsidere: I. ganho de aplicação financeira; II. transferência de estoques a clientes; III. ganho na venda de imobilizado; IV. emissão de debêntures; V. integralização do capital social; VI. ganho na venda de ações em tesouraria. São receitas os itens:`,o:[`IV, V e VI.`,`II, III e VI.`,`I, III e IV.`,`I, II e III.`],a:'D'},
{q:`A manutenção do capital em que o lucro é auferido somente se o montante dos ativos líquidos no final do período exceder o montante dos ativos líquidos no início do período, após excluir distribuições para e contribuições de sócios durante o período, é a manutenção do`,o:[`Capital Físico.`,`Capital Financeiro.`,`Capital Social.`,`Capital Integralizado.`],a:'B'},
{q:`As demonstrações contábeis são normalmente elaboradas com base na suposição de continuidade operacional. Desse modo, presume-se que a entidade não tem a intenção e nem a necessidade de`,o:[`tornar-se internacional.`,`modificar a sua atividade-fim.`,`entrar em liquidação ou deixar de negociar.`,`expandir os seus negócios para outras localidades.`],a:'C'},
{q:`Conforme a NBC TG 04 (R4) – Ativo Intangível, NÃO são exemplos de gastos a serem reconhecidos como despesa aqueles incorridos com`,o:[`atividades pré-operacionais destinadas a constituir a empresa.`,`treinamento do pessoal próprio.`,`publicidade e atividades promocionais.`,`o desenvolvimento de ativos intangíveis gerados internamente.`],a:'D'},
{q:`A Sociedade A possui 65% das ações com direito a voto da Sociedade B. Em 2023, a Sociedade B apresentou lucro de R$ 200.000. Nas demonstrações contábeis individuais da Sociedade A, pelo método da equivalência patrimonial, deve ser registrado:`,o:[`débito em Caixa e crédito em Investimentos no valor de R$ 130.000.`,`débito em Investimentos e crédito em Receita de equivalência patrimonial no valor de R$ 200.000.`,`débito em Receita de equivalência patrimonial e crédito em Investimentos no valor de R$ 200.000.`,`débito em Investimentos e crédito em Receita de equivalência patrimonial no valor de R$ 130.000.`],a:'D'},
{q:`Um ativo financeiro é mantido em modelo de negócios cujo objetivo é atingido tanto pelo recebimento de fluxos de caixa contratuais quanto pela venda de ativos financeiros. Seus fluxos de caixa são exclusivamente pagamentos de principal e juros (SPPI). Ele deve ser mensurado subsequentemente ao`,o:[`Custo Amortizado.`,`Valor Justo por Meio de Outros Resultados Abrangentes.`,`Valor Justo por Meio do Resultado.`,`Valor Realizável Líquido.`],a:'B'},
{q:`Uma sociedade constituiu provisão fiscal de R$ 5.000.000 nas demonstrações de 2023. Antes da autorização para emissão dessas demonstrações, decisão definitiva determinou recolhimento de R$ 6.000.000, confirmando condição existente em 31/12/2023. A entidade`,o:[`deve ajustar as demonstrações de 2023, reduzindo o lucro e aumentando o passivo em R$ 1.000.000.`,`deve ajustar as demonstrações de 2023 em R$ 2.000.000.`,`não deve ajustar, porque a decisão ocorreu após 31/12/2023.`,`não deve ajustar, porque a decisão ocorreu após a finalização pelo departamento contábil.`],a:'A'},
{q:`Uma máquina custou R$ 240.000 em 01/01/2020, com vida útil de 8 anos e sem valor residual. Em 31/12/2024, a vida útil total foi reavaliada para 10 anos e o valor residual passou a R$ 40.000. O valor anual da depreciação a partir da mudança é`,o:[`R$ 40.000.`,`R$ 30.000.`,`R$ 18.000.`,`R$ 10.000.`],a:'D'},
{q:`Uma entidade possui 1.000 unidades de mercadoria. O custo unitário é R$ 20, o valor realizável líquido unitário é R$ 15 e o preço de venda unitário é R$ 30. O estoque deve ser apresentado no balanço patrimonial por`,o:[`R$ 15.`,`R$ 15.000.`,`R$ 20.000.`,`R$ 30.000.`],a:'B'},
{q:`Uma companhia aérea vendeu em fevereiro 200 passagens, recebidas à vista. Os aeroportos foram fechados em maio, e os clientes realizaram as viagens em junho. Conforme a NBC TG 47, a receita deve ser reconhecida em`,o:[`janeiro.`,`fevereiro.`,`maio.`,`junho.`],a:'D'},
{q:`Em 01/07/2021, uma loja adquiriu máquina por R$ 840, estimando vida útil de 4 anos e valor residual de R$ 200. Em 01/01/2023, estimou mais 3 anos de uso e valor residual zero. O valor contábil em 31/12/2023 é`,o:[`R$ 400.`,`R$ 440.`,`R$ 320.`,`R$ 210.`],a:'A'},
{q:`Um terreno foi adquirido por R$ 180.000. No teste de recuperabilidade, o valor em uso era R$ 170.000, o valor justo R$ 190.000 e as despesas de alienação R$ 15.000. O valor do terreno após o teste é`,o:[`R$ 170.000.`,`R$ 175.000.`,`R$ 180.000.`,`R$ 190.000.`],a:'B'},
{q:`De acordo com a Lei nº 6.404/76, as Reservas de Capital poderão ser utilizadas para absorver prejuízos quando`,o:[`não houver ações em tesouraria.`,`estiverem acumulados há no mínimo três exercícios sociais.`,`ultrapassarem os lucros acumulados e as reservas de lucros.`,`houver garantia de pagamento dos dividendos mínimos obrigatórios.`],a:'C'},
{q:`Uma empresa comprou à vista aparelhos de ar-condicionado por R$ 6.000, pagou frete de R$ 200 e instalação de R$ 2.000. Na DFC pelo método direto, os caixas consumidos pelas atividades operacional e de investimento são, respectivamente`,o:[`zero e R$ 8.200.`,`R$ 200 e R$ 8.000.`,`R$ 2.000 e R$ 6.200.`,`R$ 2.200 e R$ 6.000.`],a:'A'},
{q:`Uma joalheria reconheceu: vendas de mercadorias R$ 800.000; receita financeira R$ 400.000; equivalência patrimonial R$ 200.000; venda de imobilizado R$ 170.000; aluguel a terceiros R$ 120.000. Na DVA, o valor adicionado recebido em transferência é`,o:[`R$ 490.000.`,`R$ 600.000.`,`R$ 720.000.`,`R$ 890.000.`],a:'C'},
{q:`Uma sociedade apresenta aos usuários externos informações sobre a base de preparação das demonstrações financeiras e as práticas contábeis específicas selecionadas e aplicadas para negócios e eventos significativos. Conforme a Lei nº 6.404/76, essa informação deve ser incluída`,o:[`nas Notas Explicativas.`,`no Relatório do Auditor.`,`no Relatório da Administração.`,`na Carta de Responsabilidade da Administração.`],a:'A'},
{q:`De acordo com a NBC TG 02 (R3), assinale o ativo classificado como não monetário em uma papelaria.`,o:[`Estoques.`,`Contas a receber.`,`Aplicações financeiras.`,`Adiantamento de clientes.`],a:'A'},
{q:`Conforme a Lei nº 6.404/76, no Balanço Patrimonial, as contas do ativo são apresentadas de acordo com a ordem decrescente de grau de`,o:[`liquidez.`,`relevância.`,`objetividade.`,`valor monetário.`],a:'A'},
{q:`Em 2023, a DRE apresentou Receita Líquida de R$ 200.000 e Lucro Bruto de R$ 150.000. A conta que apresenta saldo de R$ 50.000 é`,o:[`despesas de vendas.`,`despesas operacionais.`,`deduções da receita.`,`custo das mercadorias vendidas.`],a:'D'},
{q:`Uma livraria utiliza o critério PEPS (Primeiro a Entrar, Primeiro a Sair) para mensurar seus estoques. Em 01/01/2024, havia 20 livros em estoque, comprados por R$ 100 cada. Em 05/01/2024, adquiriu mais 30 unidades por R$ 120 cada. Em 10/01/2024, vendeu 35 exemplares. O custo das mercadorias vendidas em janeiro foi de`,o:[`R$ 3.500.`,`R$ 3.800.`,`R$ 4.100.`,`R$ 4.200.`],a:'B'},
{q:`Uma sociedade empresária apresenta saldo de R$ 80.000 na conta “Despesas antecipadas”. Nas demonstrações contábeis, essa conta é apresentada como`,o:[`ativo, no balanço patrimonial.`,`passivo, no balanço patrimonial.`,`outras despesas, na demonstração do resultado do exercício.`,`despesas operacionais, na demonstração do resultado do exercício.`],a:'A'},
{q:`Em abril de 2024, uma empresa de consultoria adquiriu 10 cadeiras para seus funcionários por R$ 400 cada. Metade do valor foi paga à vista e o restante será pago em junho do mesmo ano. No momento da compra, observam-se as seguintes modificações nos saldos dos elementos patrimoniais:`,o:[`aumento de R$ 2.000 no ativo e no passivo.`,`aumento de R$ 4.000 no ativo e no passivo.`,`aumento de R$ 4.000 no ativo e no patrimônio líquido.`,`diminuição de R$ 2.000 no ativo, aumento de R$ 2.000 no passivo e diminuição de R$ 4.000 no patrimônio líquido.`],a:'A'},
{q:`Uma sociedade empresária oferece serviços de entrega de documentos. Possui cinco motos para as entregas, cada uma com valor contábil de R$ 30.000, e duas motos utilizadas exclusivamente para a locomoção dos diretores, cada uma com valor contábil de R$ 50.000. A apresentação dessas motos no balanço patrimonial é`,o:[`Investimentos: R$ 250.000.`,`Ativo Imobilizado: R$ 250.000.`,`Investimentos: R$ 100.000 e Ativo Imobilizado: R$ 150.000.`,`Investimentos: R$ 150.000 e Ativo Imobilizado: R$ 100.000.`],a:'B'},
{q:`Considere os seguintes elementos das demonstrações contábeis: I. Ativo; II. Despesa; III. Receita; IV. Passivo; V. Patrimônio Líquido. Apresentam natureza devedora:`,o:[`I e II, apenas.`,`I e III, apenas.`,`II e IV, apenas.`,`I, III e V, apenas.`],a:'A'},
{q:`Uma farmácia apresentava, em 31/12/2023: aplicação financeira com vencimento em 380 dias, R$ 200.000; clientes a receber em 180 dias, R$ 140.000; disponibilidades, R$ 50.000; estoque com venda prevista em até 60 dias, R$ 120.000; imóvel onde funciona a farmácia, R$ 600.000; e móveis e utensílios, R$ 300.000. O ativo circulante era de`,o:[`R$ 170.000.`,`R$ 190.000.`,`R$ 310.000.`,`R$ 510.000.`],a:'C'},
{q:`Para o reconhecimento inicial pelo custo histórico de um ativo imobilizado, são custos diretamente atribuíveis, à exceção de`,o:[`custos de abertura de nova instalação.`,`honorários profissionais.`,`custos de frete e manuseio.`,`custos de preparação do local.`],a:'A'},
{q:`Uma entidade deseja reconhecer um ativo em seu balanço patrimonial, cuja mensuração envolve estimativas sujeitas a incertezas. Nesse caso, a entidade`,o:[`não deve reconhecer nem divulgar o ativo, pois não há objetividade em sua mensuração.`,`deve reconhecer o ativo sem mencionar a existência de estimativas.`,`não deve reconhecer o ativo, mas apenas evidenciá-lo em notas explicativas.`,`deve reconhecer o ativo e descrever e explicar as estimativas de forma clara e precisa, pois estimativas razoáveis são parte essencial da elaboração das informações financeiras.`],a:'D'},
{q:`Em 2023, uma entidade desreconheceu um ativo de seu balanço patrimonial. Uma possível causa para o desreconhecimento é`,o:[`a entidade decidir utilizar um terreno para finalidade diferente.`,`a entidade perder o controle de um imóvel por decisão judicial.`,`a entidade renegociar o prazo de recebimento de clientes em situação financeira difícil.`,`a entidade constatar que suas máquinas poderão ser utilizadas por tempo maior que a vida útil prevista.`],a:'B'},
{q:`De acordo com o conceito de manutenção de capital financeiro, o lucro é auferido somente se o montante financeiro dos ativos líquidos no final do período exceder o montante financeiro dos ativos líquidos no início do período, após excluir`,o:[`compra e venda de ativos fixos durante o período.`,`distribuições para, e contribuições de, sócios durante o período.`,`reconhecimento contábil de receitas e de despesas durante o período.`,`recebimento de receitas e pagamentos de despesas durante o período.`],a:'B'},
{q:`Uma empresa apresentava, em seu Balanço Patrimonial de 2023, valor líquido contábil de R$ 400.000 correspondente a uma máquina (custo de aquisição de R$ 500.000 e depreciação acumulada de R$ 100.000). No teste de recuperabilidade em 31/12/2023, o valor em uso foi R$ 380.000 e o valor justo líquido da despesa de venda foi R$ 390.000. O valor recuperável da máquina é`,o:[`R$ 400.000.`,`R$ 390.000.`,`R$ 380.000.`,`R$ 500.000.`],a:'B'},
{q:`Uma entidade possui imóvel para renda avaliado pelo valor justo. O valor contábil no início do exercício era R$ 1.000. Ao final, o valor de mercado do imóvel era R$ 1.120. Caso fosse vendido, haveria pagamento de R$ 50 a um corretor. O valor justo do imóvel na data de encerramento é`,o:[`R$ 1.070.`,`R$ 1.000.`,`R$ 1.170.`,`R$ 1.120.`],a:'D'},
{q:`De acordo com o CPC 22 – Informações por Segmento, dois ou mais segmentos operacionais podem ser agregados se tiverem características econômicas semelhantes e forem semelhantes em certos aspectos, à exceção de`,o:[`natureza dos processos de produção ou de distribuição.`,`tipo ou categoria de clientes dos seus produtos e serviços.`,`resultados em termos absolutos iguais.`,`se aplicável, a natureza do ambiente regulatório.`],a:'C'},
{q:`Em relação à estruturação das Normas Brasileiras de Contabilidade Técnicas, analise: I. São convergentes com as normas internacionais emitidas pelo IASB. II. São convergentes com as normas norte-americanas emitidas pelo FASB. III. São editadas por necessidades locais, sem equivalentes internacionais. As NBC TG estão relacionadas ao que se afirma em`,o:[`I, somente.`,`I e II, somente.`,`I e III, somente.`,`II e III, somente.`],a:'C'},
{q:`De acordo com a NBC TG Estrutura Conceitual, os principais usuários aos quais se destinam os relatórios financeiros para fins gerais são representados por`,o:[`empregados, clientes e fornecedores.`,`detentores de participação societária e interessados em adquiri-la.`,`população em geral, impactada direta e indiretamente pelos relatórios.`,`investidores, credores por empréstimos e outros credores, existentes e potenciais.`],a:'D'},
{q:`Em 01/01/2024, o estoque de uma loja de brinquedos, formado por 10 bonecas, era de R$ 500. Em janeiro ocorreram: compra de 20 unidades a R$ 62; venda de 12 unidades; compra de 15 unidades a R$ 69; e venda de 18 unidades. Pelo método do Custo Médio Ponderado Móvel, o valor do estoque final em 31/01/2024 é`,o:[`R$ 376,30.`,`R$ 758,33.`,`R$ 925,00.`,`R$ 945,00.`],a:'D'},
{q:`Uma joalheria possui três imóveis: um onde realiza as vendas, avaliado em R$ 900.000; outro alugado a terceiros, avaliado em R$ 700.000; e um terceiro utilizado como escritório administrativo, avaliado em R$ 500.000. Considerando apenas esses fatos, o saldo do ativo imobilizado é`,o:[`R$ 500.000.`,`R$ 900.000.`,`R$ 1.400.000.`,`R$ 2.100.000.`],a:'C'},
{q:`Em 31/12/2023, a Cia Lua apresentava: aplicações financeiras com vencimento em 720 dias, R$ 70.000; clientes a receber em 380 dias, R$ 60.000; disponibilidades, R$ 50.000; estoques com venda prevista em até 180 dias, R$ 40.000; perdas estimadas com crédito de liquidação duvidosa, R$ 6.000; e perdas estimadas com desvalorização de estoque, R$ 8.000. O saldo do ativo circulante era`,o:[`R$ 76.000.`,`R$ 82.000.`,`R$ 90.000.`,`R$ 136.000.`],a:'B'},
{q:`De acordo com a NBC TG 26 (R5), além dos itens requeridos em outras normas, a demonstração do resultado do período deve incluir as rubricas a seguir, com exceção de`,o:[`custos de financiamento.`,`distribuição do resultado do período.`,`parcela dos resultados de empresas investidas reconhecida pelo método da equivalência patrimonial.`,`ganhos e perdas decorrentes do desreconhecimento de ativos financeiros mensurados pelo custo amortizado.`],a:'B'},
{q:`Resultado abrangente é a mutação que ocorre no ______ durante um período, resultante de transações e outros eventos que não sejam derivados de transações com os sócios na qualidade de proprietários. A lacuna é preenchida por`,o:[`ativo.`,`passivo.`,`resultado.`,`patrimônio líquido.`],a:'D'},
{q:`Uma empresa de auditoria independente elabora a Demonstração dos Fluxos de Caixa pelo método indireto. Para calcular o lucro ajustado, deve adicionar ao lucro líquido, como ajuste, a despesa de`,o:[`aluguel de imóveis.`,`salários de empregados.`,`salários de mão de obra terceirizada.`,`depreciação dos ativos imobilizados.`],a:'D'},
{q:`Uma empresa de perícia contábil apresentou em 2023: prestação de serviços, R$ 200.000; venda de ativo imobilizado, R$ 120.000; equivalência patrimonial, R$ 50.000; e receitas financeiras, R$ 30.000. O valor adicionado recebido em transferência na DVA é`,o:[`R$ 50.000.`,`R$ 80.000.`,`R$ 200.000.`,`R$ 320.000.`],a:'B'},
{q:`A Cia A controla 90% do capital social da Cia B. No balanço patrimonial, a participação dos não controladores deve ser apresentada`,o:[`no passivo, no balanço patrimonial consolidado.`,`no passivo, no balanço patrimonial individual da Cia A.`,`no patrimônio líquido, no balanço patrimonial individual da Cia A.`,`no patrimônio líquido, no balanço patrimonial consolidado.`],a:'D'},
{q:`A Cia Alfa fechou o exercício em 31/12/2023. Em 10/01/2024, a Cia Beta cometeu o erro de aumentar os saldos em R$ 200.000 quando deveria tê-los diminuído em R$ 200.000. Após corrigir o erro e eliminar a conta Suprimentos na reclassificação, os totais corretos do ativo e do passivo no balanço patrimonial reclassificado em 31/01/2024 são`,o:[`R$ 890.000 = R$ 920.000.`,`R$ 950.000 = R$ 920.000.`,`R$ 890.000 = R$ 520.000.`,`R$ 520.000 = R$ 520.000.`],a:'C'},
{q:`Uma sociedade empresária apresenta itens monetários em moeda estrangeira. De acordo com a NBC TG 02 (R3), esses itens devem ser convertidos utilizando-se a taxa de câmbio`,o:[`média anual.`,`de fechamento.`,`vigente na data da transação.`,`estimada para a data de vencimento dos itens monetários.`],a:'B'},
{q:`Joana comprou ingresso de R$ 400 para um show que começou com grande atraso, fazendo com que ela não pudesse assisti-lo. Ela ajuizou ação pedindo devolução do ingresso e R$ 1.000 por danos morais. Os advogados avaliaram a perda da devolução como provável e a dos danos morais como possível. O valor da provisão a reconhecer é`,o:[`zero.`,`R$ 400.`,`R$ 1.000.`,`R$ 1.400.`],a:'B'},
{q:`Em relação aos ativos no Balanço Patrimonial de uma entidade, assinale a alternativa correta de acordo com a Lei nº 6.404/76.`,o:[`No intangível estão as participações permanentes em outras sociedades e os direitos de qualquer natureza não classificáveis no ativo circulante.`,`No imobilizado estão os direitos sobre bens incorpóreos destinados à manutenção da companhia.`,`Em investimentos estão os direitos sobre bens corpóreos destinados à manutenção das atividades da entidade.`,`No circulante estão as disponibilidades, os direitos realizáveis no curso do exercício social subsequente e as aplicações de recursos em despesas do exercício seguinte.`],a:'D'},
{q:`Uma sociedade empresária apresentava capital autorizado de R$ 500.000, capital a integralizar de R$ 40.000 e capital a subscrever de R$ 80.000. O capital social realizado em 31/12/2023 é`,o:[`R$ 380.000.`,`R$ 420.000.`,`R$ 460.000.`,`R$ 540.000.`],a:'A'},
{q:`Avalie as contas: I. Adiantamento a sócio; II. Receitas antecipadas; III. Ações em tesouraria. São contas de natureza devedora`,o:[`I, II e III.`,`I e II, somente.`,`I e III, somente.`,`II e III, somente.`],a:'C'},
{q:`Em 01/01/2024, Clara matriculou seus filhos em aulas de natação por meio de pacote semestral de R$ 4.200, pago à vista. Não haveria aulas em abril, e o pacote teria validade até 31/07/2024. As crianças iniciaram as aulas em janeiro. Pelo regime de competência, a receita reconhecida pela escola em janeiro de 2024 é`,o:[`zero.`,`R$ 600.`,`R$ 700.`,`R$ 4.200.`],a:'C'}
];
const $=s=>document.querySelector(s), TOTAL=questions.length, letters=['A','B','C','D'];
let current=Number(localStorage.getItem('cfcq-last')||1), selected=null;
let answers=JSON.parse(localStorage.getItem('cfcq-answers')||'{}');
let favorites=new Set(JSON.parse(localStorage.getItem('cfcq-favs')||'[]'));
const screens=['home','quizScreen','resultScreen','listScreen'];
function image(n){return `imagens/${String(n).padStart(2,'0')}.png`}
function save(){localStorage.setItem('cfcq-last',current);localStorage.setItem('cfcq-answers',JSON.stringify(answers));localStorage.setItem('cfcq-favs',JSON.stringify([...favorites]));}
function show(id){screens.forEach(s=>$('#'+s).classList.toggle('hidden',s!==id));window.scrollTo(0,0)}
function stats(){const vals=Object.values(answers),correct=vals.filter(x=>x.correct).length,wrong=vals.length-correct,pct=vals.length?Math.round(correct/vals.length*100):0;$('#answeredHome').textContent=vals.length;$('#correctHome').textContent=correct;$('#wrongHome').textContent=wrong;$('#percentHome').textContent=pct+'%';$('#continueBtn').style.display=localStorage.getItem('cfcq-last')?'block':'none'}
function renderQuiz(){selected=answers[current]?.choice||null;const data=questions[current-1];$('#questionCounter').textContent=`Questão ${current} de ${TOTAL}`;$('#progressBar').style.width=`${current/TOTAL*100}%`;$('#questionText').textContent=data.q;$('#options').innerHTML='';data.o.forEach((text,i)=>{const l=letters[i],b=document.createElement('button');b.className='option'+(selected===l?' selected':'');b.innerHTML=`<span class="option-letter">${l}</span><span>${text}</span>`;b.onclick=()=>{selected=l;document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#confirmBtn').disabled=false;$('#selectionHint').textContent=`Alternativa ${l} selecionada.`};$('#options').appendChild(b)});const a=answers[current];const badge=$('#statusBadge');badge.className='status-badge'+(a?(a.correct?' correct':' wrong'):'');badge.textContent=a?(a.correct?'Acertou':'Errou'):'Não respondida';$('#confirmBtn').disabled=!selected;$('#confirmBtn').textContent=a?'VER RESULTADO':'CONFIRMAR RESPOSTA';$('#prevQuestion').disabled=current===1;$('#nextQuestion').disabled=current===TOTAL;$('#favBtn').textContent=favorites.has(current)?'★':'☆';show('quizScreen')}
function submitAnswer(){if(!selected)return;const correct=selected===questions[current-1].a;answers[current]={choice:selected,correct};save();renderResult()}
function renderResult(){const a=answers[current];if(!a){renderQuiz();return}const right=questions[current-1].a;$('#feedback').className='feedback '+(a.correct?'correct':'wrong');$('#feedback').textContent=a.correct?'✅ ACERTOU!':'❌ ERROU!';$('#yourAnswer').textContent=`Sua resposta: ${a.choice}`;$('#rightAnswer').textContent=`Gabarito: ${right}`;$('#resolutionImage').src=image(current);$('#resolutionImage').alt=`Resolução da questão ${current}`;$('#nextAfterResult').textContent=current<TOTAL?'Próxima ▶':'Ver resultado geral';$('#favBtn').textContent=favorites.has(current)?'★':'☆';show('resultScreen')}
function go(n){current=Math.max(1,Math.min(TOTAL,n));save();renderQuiz()}
function buildList(mode='all'){let nums=[...Array(TOTAL)].map((_,i)=>i+1);if(mode==='favorites')nums=nums.filter(n=>favorites.has(n));if(mode==='errors')nums=nums.filter(n=>answers[n]&&!answers[n].correct);$('#listTitle').textContent=mode==='favorites'?'Favoritas':mode==='errors'?'Questões erradas':'Todas as questões';const g=$('#questionGrid');g.innerHTML='';if(!nums.length){g.innerHTML='<p>Nenhuma questão nesta lista.</p>';show('listScreen');return}nums.forEach(n=>{const a=answers[n],b=document.createElement('button');b.className='q-card '+(a?(a.correct?'correct':'wrong'):'')+(favorites.has(n)?' fav':'');b.innerHTML=`<img src="${image(n)}" loading="lazy" alt="Questão ${n}"><b>Questão ${n}</b><div class="q-state">${a?(a.correct?'✅ Acertou':'❌ Errou'):'⚪ Não respondeu'}</div>`;b.onclick=()=>go(n);g.appendChild(b)});show('listScreen')}
function drawer(open){$('#drawer').classList.toggle('open',open);$('#overlay').classList.toggle('show',open)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)}
$('#startBtn').onclick=()=>go(1);$('#continueBtn').onclick=()=>go(current);$('#confirmBtn').onclick=submitAnswer;$('#prevQuestion').onclick=()=>go(current-1);$('#nextQuestion').onclick=()=>go(current+1);$('#listBtn').onclick=()=>buildList('all');$('#backHome').onclick=()=>{stats();show('home')};$('#backToQuestion').onclick=renderQuiz;$('#nextAfterResult').onclick=()=>{if(current<TOTAL)go(current+1);else{stats();show('home')}};$('#favBtn').onclick=()=>{favorites.has(current)?favorites.delete(current):favorites.add(current);save();$('#favBtn').textContent=favorites.has(current)?'★':'☆';toast(favorites.has(current)?'Adicionada às favoritas':'Removida das favoritas')};$('#zoomBtn').onclick=()=>{$('#zoomImage').src=image(current);$('#zoomModal').classList.add('show')};$('#closeZoom').onclick=()=>$('#zoomModal').classList.remove('show');$('#menuBtn').onclick=()=>drawer(true);$('#closeDrawer').onclick=()=>drawer(false);$('#overlay').onclick=()=>drawer(false);$('#drawer').onclick=e=>{const a=e.target.dataset.action;if(!a)return;drawer(false);if(a==='home'){stats();show('home')}if(a==='goto'){const n=Number(prompt(`Digite uma questão de 1 a ${TOTAL}:`));if(n>=1&&n<=TOTAL)go(n)}if(a==='all')buildList('all');if(a==='favorites')buildList('favorites');if(a==='errors')buildList('errors');if(a==='reset'&&window.confirm('Deseja apagar respostas, desempenho e favoritas?')){answers={};favorites=new Set();current=1;save();stats();show('home');toast('Desempenho reiniciado')}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));
stats();show('home');
