const questions=[
{q:`Desreconhecimento é a retirada de parte ou da totalidade de ativo ou passivo reconhecido do balanço patrimonial da entidade. A máquina utilizada para a produção do principal produto de uma entidade deve ser desreconhecida quando`,o:[`perder todo o potencial de produzir benefícios econômicos para a entidade.`,`estiver parcialmente depreciada.`,`sofrer perda de valor recuperável.`,`estiver sob controle da entidade.`],a:'A'},
{q:`Conforme a NBC TG – Estrutura Conceitual, uma receita reflete aumento nos ativos, ou redução nos passivos, que resultam em aumentos no patrimônio líquido, exceto contribuições de detentores de direitos sobre o patrimônio.\n\nConsidere: I. ganho de aplicação financeira; II. transferência de estoques a clientes; III. ganho na venda de imobilizado; IV. emissão de debêntures; V. integralização do capital social; VI. ganho na venda de ações em tesouraria. São receitas os itens:`,o:[`IV, V e VI.`,`II, III e VI.`,`I, III e IV.`,`I, II e III.`],a:'D'},
{q:`A manutenção do capital em que o lucro é auferido somente se o montante dos ativos líquidos no final do período exceder o montante dos ativos líquidos no início do período, após excluir distribuições para e contribuições de sócios durante o período, é a manutenção do`,o:[`Capital Físico.`,`Capital Financeiro.`,`Capital Social.`,`Capital Integralizado.`],a:'B'},
{q:`As demonstrações contábeis são normalmente elaboradas com base na suposição de continuidade operacional. Desse modo, presume-se que a entidade não tem a intenção e nem a necessidade de`,o:[`tornar-se internacional.`,`modificar a sua atividade-fim.`,`entrar em liquidação ou deixar de negociar.`,`expandir os seus negócios para outras localidades.`],a:'C'},
{q:`Conforme a NBC TG 04 (R4) – Ativo Intangível, NÃO são exemplos de gastos a serem reconhecidos como despesa aqueles incorridos com`,o:[`atividades pré-operacionais destinadas a constituir a empresa.`,`treinamento do pessoal próprio.`,`publicidade e atividades promocionais.`,`o desenvolvimento de ativos intangíveis gerados internamente.`],a:'D'},
{q:`A Sociedade A possui 65% das ações com direito a voto da Sociedade B. Em 2023, a Sociedade B apresentou lucro de R$ 200.000. Nas demonstrações contábeis individuais da Sociedade A, pelo método da equivalência patrimonial, deve ser registrado:`,o:[`débito em Caixa e crédito em Investimentos no valor de R$ 130.000.`,`débito em Investimentos e crédito em Receita de equivalência patrimonial no valor de R$ 200.000.`,`débito em Receita de equivalência patrimonial e crédito em Investimentos no valor de R$ 200.000.`,`débito em Investimentos e crédito em Receita de equivalência patrimonial no valor de R$ 130.000.`],a:'D'},
{q:`Um ativo financeiro é mantido em modelo de negócios cujo objetivo é atingido tanto pelo recebimento de fluxos de caixa contratuais quanto pela venda de ativos financeiros. Seus fluxos de caixa são exclusivamente pagamentos de principal e juros (SPPI). Ele deve ser mensurado subsequentemente ao`,o:[`Custo Amortizado.`,`Valor Justo por Meio de Outros Resultados Abrangentes.`,`Valor Justo por Meio do Resultado.`,`Valor Realizável Líquido.`],a:'B'},
{q:`Uma sociedade constituiu provisão fiscal de R$ 5.000.000 nas demonstrações de 2023. Antes da autorização para emissão dessas demonstrações, decisão definitiva determinou recolhimento de R$ 6.000.000, confirmando condição existente em 31/12/2023. A entidade`,o:[`deve ajustar as demonstrações de 2023, reduzindo o lucro e aumentando o passivo em R$ 1.000.000.`,`deve ajustar as demonstrações de 2023 em R$ 2.000.000.`,`não deve ajustar, porque a decisão ocorreu após 31/12/2023.`,`não deve ajustar, porque a decisão ocorreu após a finalização pelo departamento contábil.`],a:'A'},
{q:`Uma máquina custou R$ 240.000 em 01/01/2020, com vida útil de 8 anos e sem valor residual. Em 31/12/2024, a vida útil total foi reavaliada para 10 anos e o valor residual passou a R$ 40.000. O valor anual da depreciação a partir da mudança é`,o:[`R$ 40.000.`,`R$ 30.000.`,`R$ 18.000.`,`R$ 10.000.`],a:'D'},
{q:`Uma entidade possui 1.000 unidades de mercadoria. O custo unitário é R$ 20, o valor realizável líquido unitário é R$ 15 e o preço de venda unitário é R$ 30. O estoque deve ser apresentado no balanço patrimonial por`,o:[`R$ 15.`,`R$ 15.000.`,`R$ 20.000.`,`R$ 30.000.`],a:'B'},
{q:`Uma companhia aérea vendeu em fevereiro 200 passagens, recebidas à vista. Os aeroportos foram fechados em maio, e os clientes realizaram as viagens em junho. Conforme a NBC TG 47, a receita deve ser reconhecida em`,o:[`janeiro.`,`fevereiro.`,`maio.`,`junho.`],a:'D'},
{q:`Em 01/07/2021, uma loja adquiriu máquina por R$ 840, estimando vida útil de 4 anos e valor residual de R$ 200. Em 01/01/2023, estimou mais 3 anos de uso e valor residual zero. O valor contábil em 31/12/2023 é`,o:[`R$ 400.`,`R$ 440.`,`R$ 320.`,`R$ 210.`],a:'A'},
{q:`Um terreno foi adquirido por R$ 180.000. No teste de recuperabilidade, o valor em uso era R$ 170.000, o valor justo R$ 190.000 e as despesas de alienação R$ 15.000. O valor do terreno após o teste é`,o:[`R$ 170.000.`,`R$ 175.000.`,`R$ 180.000.`,`R$ 190.000.`],a:'B'},
{q:`De acordo com a Lei nº 6.404/76, as Reservas de Capital poderão ser utilizadas para absorver prejuízos quando`,o:[`não houver ações em tesouraria.`,`estiverem acumulados há no mínimo três exercícios sociais.`,`ultrapassarem os lucros acumulados e as reservas de lucros.`,`houver garantia de pagamento dos dividendos mínimos obrigatórios.`],a:'C'},
{q:`Uma empresa comprou à vista aparelhos de ar-condicionado por R$ 6.000, pagou frete de R$ 200 e instalação de R$ 2.000. Na DFC pelo método direto, os caixas consumidos pelas atividades operacional e de investimento são, respectivamente`,o:[`zero e R$ 8.200.`,`R$ 200 e R$ 8.000.`,`R$ 2.000 e R$ 6.200.`,`R$ 2.200 e R$ 6.000.`],a:'A'},
{q:`Uma joalheria reconheceu: vendas de mercadorias R$ 800.000; receita financeira R$ 400.000; equivalência patrimonial R$ 200.000; venda de imobilizado R$ 170.000; aluguel a terceiros R$ 120.000. Na DVA, o valor adicionado recebido em transferência é`,o:[`R$ 490.000.`,`R$ 600.000.`,`R$ 720.000.`,`R$ 890.000.`],a:'C'},
{q:`Uma sociedade apresenta aos usuários externos informações sobre a base de preparação das demonstrações financeiras e as práticas contábeis específicas selecionadas e aplicadas para negócios e eventos significativos. Conforme a Lei nº 6.404/76, essa informação deve ser incluída`,o:[`nas Notas Explicativas.`,`no Relatório do Auditor.`,`no Relatório da Administração.`,`na Carta de Responsabilidade da Administração.`],a:'A'},
{q:`De acordo com a NBC TG 02 (R3), assinale o ativo classificado como não monetário em uma papelaria.`,o:[`Estoques.`,`Contas a receber.`,`Aplicações financeiras.`,`Adiantamento de clientes.`],a:'A'},
{q:`Conforme a Lei nº 6.404/76, no Balanço Patrimonial, as contas do ativo são apresentadas de acordo com a ordem decrescente de grau de`,o:[`liquidez.`,`relevância.`,`objetividade.`,`valor monetário.`],a:'A'},
{q:`Em 2023, a DRE apresentou Receita Líquida de R$ 200.000 e Lucro Bruto de R$ 150.000. A conta que apresenta saldo de R$ 50.000 é`,o:[`despesas de vendas.`,`despesas operacionais.`,`deduções da receita.`,`custo das mercadorias vendidas.`],a:'D'}
];
const $=s=>document.querySelector(s), TOTAL=questions.length, letters=['A','B','C','D'];
let current=Number(localStorage.getItem('cfcq-last')||1), selected=null;
let answers=JSON.parse(localStorage.getItem('cfcq-answers')||'{}');
let favorites=new Set(JSON.parse(localStorage.getItem('cfcq-favs')||'[]'));
const screens=['home','quizScreen','resultScreen','listScreen'];
function image(n){return `imagens/${String(n).padStart(2,'0')}.png`}
function save(){localStorage.setItem('cfcq-last',current);localStorage.setItem('cfcq-answers',JSON.stringify(answers));localStorage.setItem('cfcq-favs',JSON.stringify([...favorites]));}
function show(id){screens.forEach(s=>$('#'+s).classList.toggle('hidden',s!==id));window.scrollTo(0,0)}
function stats(){const vals=Object.values(answers),correct=vals.filter(x=>x.correct).length,wrong=vals.length-correct,pct=vals.length?Math.round(correct/vals.length*100):0;$('#answeredHome').textContent=vals.length;$('#correctHome').textContent=correct;$('#wrongHome').textContent=wrong;$('#percentHome').textContent=pct+'%';$('#continueBtn').style.display=localStorage.getItem('cfcq-last')?'block':'none'}
function renderQuiz(){selected=answers[current]?.choice||null;const data=questions[current-1];$('#questionCounter').textContent=`Questão ${current} de ${TOTAL}`;$('#progressBar').style.width=`${current/TOTAL*100}%`;$('#questionText').textContent=data.q;$('#options').innerHTML='';data.o.forEach((text,i)=>{const l=letters[i],b=document.createElement('button');b.className='option'+(selected===l?' selected':'');b.innerHTML=`<span class="option-letter">${l}</span><span>${text}</span>`;b.onclick=()=>{selected=l;document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#confirmBtn').disabled=false;$('#selectionHint').textContent=`Alternativa ${l} selecionada.`};$('#options').appendChild(b)});const a=answers[current];const badge=$('#statusBadge');badge.className='status-badge'+(a?(a.correct?' correct':' wrong'):'');badge.textContent=a?(a.correct?'Acertou':'Errou'):'Não respondida';$('#confirmBtn').disabled=!selected;$('#confirmBtn').textContent=a?'VER RESULTADO':'CONFIRMAR RESPOSTA';$('#prevQuestion').disabled=current===1;$('#nextQuestion').disabled=current===TOTAL;$('#favBtn').textContent=favorites.has(current)?'★':'☆';show('quizScreen')}
function submitAnswer(){if(!selected)return;const correct=selected===questions[current-1].a;answers[current]={choice:selected,correct};save();renderResult()}
function renderResult(){const a=answers[current];if(!a){renderQuiz();return}const right=questions[current-1].a;$('#feedback').className='feedback '+(a.correct?'correct':'wrong');$('#feedback').textContent=a.correct?'✅ ACERTOU!':'❌ ERROU!';$('#yourAnswer').textContent=`Sua resposta: ${a.choice}`;$('#rightAnswer').textContent=`Gabarito: ${right}`;$('#resolutionImage').src=image(current);$('#resolutionImage').alt=`Resolução da questão ${current}`;$('#nextAfterResult').textContent=current<TOTAL?'Próxima ▶':'Ver resultado geral';$('#favBtn').textContent=favorites.has(current)?'★':'☆';show('resultScreen')}
function go(n){current=Math.max(1,Math.min(TOTAL,n));save();renderQuiz()}
function buildList(mode='all'){let nums=[...Array(TOTAL)].map((_,i)=>i+1);if(mode==='favorites')nums=nums.filter(n=>favorites.has(n));if(mode==='errors')nums=nums.filter(n=>answers[n]&&!answers[n].correct);$('#listTitle').textContent=mode==='favorites'?'Favoritas':mode==='errors'?'Questões erradas':'Todas as questões';const g=$('#questionGrid');g.innerHTML='';if(!nums.length){g.innerHTML='<p>Nenhuma questão nesta lista.</p>';show('listScreen');return}nums.forEach(n=>{const a=answers[n],b=document.createElement('button');b.className='q-card '+(a?(a.correct?'correct':'wrong'):'')+(favorites.has(n)?' fav':'');b.innerHTML=`<img src="${image(n)}" loading="lazy" alt="Questão ${n}"><b>Questão ${n}</b><div class="q-state">${a?(a.correct?'✅ Acertou':'❌ Errou'):'⚪ Não respondeu'}</div>`;b.onclick=()=>go(n);g.appendChild(b)});show('listScreen')}
function drawer(open){$('#drawer').classList.toggle('open',open);$('#overlay').classList.toggle('show',open)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)}
$('#startBtn').onclick=()=>go(1);$('#continueBtn').onclick=()=>go(current);$('#confirmBtn').onclick=submitAnswer;$('#prevQuestion').onclick=()=>go(current-1);$('#nextQuestion').onclick=()=>go(current+1);$('#listBtn').onclick=()=>buildList('all');$('#backHome').onclick=()=>{stats();show('home')};$('#backToQuestion').onclick=renderQuiz;$('#nextAfterResult').onclick=()=>{if(current<TOTAL)go(current+1);else{stats();show('home')}};$('#favBtn').onclick=()=>{favorites.has(current)?favorites.delete(current):favorites.add(current);save();$('#favBtn').textContent=favorites.has(current)?'★':'☆';toast(favorites.has(current)?'Adicionada às favoritas':'Removida das favoritas')};$('#zoomBtn').onclick=()=>{$('#zoomImage').src=image(current);$('#zoomModal').classList.add('show')};$('#closeZoom').onclick=()=>$('#zoomModal').classList.remove('show');$('#menuBtn').onclick=()=>drawer(true);$('#closeDrawer').onclick=()=>drawer(false);$('#overlay').onclick=()=>drawer(false);$('#drawer').onclick=e=>{const a=e.target.dataset.action;if(!a)return;drawer(false);if(a==='home'){stats();show('home')}if(a==='goto'){const n=Number(prompt(`Digite uma questão de 1 a ${TOTAL}:`));if(n>=1&&n<=TOTAL)go(n)}if(a==='all')buildList('all');if(a==='favorites')buildList('favorites');if(a==='errors')buildList('errors');if(a==='reset'&&window.confirm('Deseja apagar respostas, desempenho e favoritas?')){answers={};favorites=new Set();current=1;save();stats();show('home');toast('Desempenho reiniciado')}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));
stats();show('home');
